version: "3"
services:
  # this container will run Cypress test using built-in Electron browser
  e2e:
    image: "my-image:v1.1"
    command: "cy:e2e"
    volumes:
      - ./cypress/videos:/mflorenzoCypress/cypress/videos
      - ./cypress/reports:/mflorenzoCypress/cypress/reports

  # this container will run Cypress test using Chrome browser
  e2e-chrome:
    image: "my-image:v1.1"
    command: "chrome:test"
    volumes:
      - ./cypress/videos:/mflorenzoCypress/cypress/videos
      - ./cypress/reports:/mflorenzoCypress/cypress/reports

  # this container will run Cypress test using Firefox browser
  # note that both Chrome and Firefox browsers were pre-installed in the Docker image
  e2e-firefox:
    image: "my-image:v1.1"
    command: "firefox:test"
    # if you want to debug FF run, pass DEBUG variable like
    environment:
      - DEBUG=cypress:server:browsers:firefox-util,cypress:server:util:process_profiler
    volumes:
      - ./cypress/videos:/mflorenzoCypress/cypress/videos
      - ./cypress/reports:/mflorenzoCypress/cypress/reports