name: e2e

on: 
  push:
    branches: [main]
  pull_request:
  
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Cancel previous run
        if: github.ref != 'refs/heads/main'
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Dependencies
        run: npm install && npx cypress install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/e2e/automationPractice.cy.js
          command: npm run cypress:e2e

      - name: screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 1
          